# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gq-ed0azgI3_1_fvJUMtNF2bjwSRWOkX

Write a Python Program for Fibonacci numbers.
"""

num1,num2=0,1
sum=num1+num2
n=int(input("enter n value: "))
if n>1:
 print(num1,end=" ") 
 print(num2,end=" ")
 for i in range(n-2):
   print(sum,end=" ")
   num1=num2
   num2=sum
   sum=num1+num2