# -*- coding: utf-8 -*-
"""Let's Code!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gq-ed0azgI3_1_fvJUMtNF2bjwSRWOkX

Taks 1: write a Python program which accepts the radius of a circle from the user and computes area.
"""

import math
r=float(input("enter the radius: "))
print("area of the cirlce is: ",math.pi*r**2)

"""Task 2: write a Python program to accept a filename from the user and print the extension of that."""

filename=input("enter the file name: ")
extension=filename.split(".")
if extension[1]=="py":
  print("The extension of the file is : ","python")
else :
  print("The extension of the file is : ",extension[1])